### ISSUE TITLE
API to trigger bug reporter from another module

### ISSUE THREAD

**Issue by ruipin** [League-of-Foundry-Developers/bug-reporter#103]
As part of https://github.com/ruipin/fvtt-lib-wrapper/issues/42, I want to add the possibility for libWrapper to provide a "Report this issue here" button, which opens Bug Reporter if it is installed.

For this to be possible, I would need some way to:

1. Query bug reporter as to whether a module ID allows bug-reporter to be used.

2. Request bug reporter to start the bug submission workflow on a specific module ID, and pre-fill a specific title and technical details.

This could, of course, be the same API (e.g. the method could return `false` if the module has not opted in, otherwise it starts the bug report workflow and returns `true`).

**Comment by Ethck** [comment]
This is a great idea! I should have some cycles this weekend, so I'll let you know what I come up with.

**Comment by ruipin** [comment]
That's good to hear, thanks!

Note that I will not be working on the dialog for a while (I plan to only work on the simpler tasks for that libWrapper issue this weekend, that issue has a lot to be done before this API will become relevant) so please take your time.
