### ISSUE TITLE
When closing the Bug reporter

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/bug-reporter#112]
**Submitted By**: Toandry#6321 (discord)
**Feedback Type**: Bug
 
**Core:** 0.8.6
**System:** dnd5e v1.3.6
**Module Version:** bug-reporter v1.3.1
 
**Description**:
To be honest, I'm reporting this mainly to try out the Bug Reporter module.

Anyway, when I close the first window it sends into the console an error : Uncaught (in promise) undefined.

That's all :).<details>
<summary>Active Modules</summary>

about-time--v1.0.3;
acelib--v1.1.2;
ActiveAuras--v0.3.03;
advanced-macros--v1.9;
ambientdoors--v2.2.4;
arbron-hp-bar--v2.0.3;
autoanimations--v0.4.11;
autocomplete-inline-properties--v2.1.1;
autorotate--vv1.2.1;
babele--v2.0.6;
better-rolltables--v1.6.14;
Border-Control--v1.2.05;
bug-reporter--v1.3.1;
calendar-weather--v3.1.6;
chat-notifications--v1.2.3;
chat-portrait--v0.3.8;
colorsettings--v2.5.9;
combat-utility-belt--v1.6.0;
CommunityLighting--v0.4.7;
compendium-folders--v2.3.2;
custom-hotbar--v2.1.0;
Custom-Token-Animations--v0.2.51;
D&D_Rules--v1.0.0;
dae--v0.8.29;
df-settings-clarity--v3.2.0;
dfreds-droppables--v1.2.7;
dfreds-pocket-change--v2.0.5;
dice-calculator--v1.1.0;
dice-so-nice--v4.0.6;
dnd5e-helpers--v2.0.8;
dnd5e_fr-FR--v1.33.0;
drag-ruler--v1.7.7;
Dynamic-Effects-SRD--v5.0.01;
easy-target--v2.12;
EasyTable--v1.3.3;
find-the-culprit--v1.3.3;
forien-copy-environment--v2.0.5;
forien-quest-log--v0.6.0;
foundryvtt-simple-calendar--vv1.3.0;
foundry_community_macros--v0.43.0;
fr-core--v0.8.8.0;
fxmaster--v1.2.1;
initiative-double-click--v1.0;
innocenti-openlock--v0.4.2;
itemacro--vv1.5.3;
jb2a_patreon--v0.2.2;
keybind-lib--v0.3.2;
lessfog--v0.8.5;
lets-trade-5e--v0.3.0;
lib-df-hotkeys--v2.3.4;
lib-wrapper--v1.7.5.0;
lmrtfy--v1.17;
LockView--v1.4.12;
lootsheetnpc5e--v3.1.0;
macro-folders--v1.2.22;
macroeditor--v1.0.9;
mce-config--v0.0.4;
midi-qol--v0.8.33;
monks-little-details--v1.0.34;
monks-scene-navigation--v1.0.14;
monks-tokenbar--v1.0.45;
moulinette-core--v3.1.8;
moulinette-gameicons--v2.1.0;
moulinette-imagesearch--v2.3.0;
moulinette-scenes--v2.7.0;
moulinette-sounds--v2.6.0;
moulinette-tiles--v3.1.1;
multilevel-tokens--v1.5.1;
otigons_animation_macros--v0.1.4;
parallaxia--v0.3.2;
perfect-vision--v1.9.14;
permission_viewer--v0.8.7;
pointer--v2.3.3;
polyglot--v1.7.1.1;
popout--v2.0;
quick-insert--v2.4.7;
scene-packer--v2.2.25;
select-tool-everywhere--v1.2.0;
sequencer--v0.4.6;
SharedCompendiums--v1.0.0;
socketlib--v1.0.8;
spellTemplateManager--v2.1.3;
split-journal--v1.1;
tabletop-rpg-music--v1.3.0;
tidy-ui_game-settings--v0.1.23;
tidy5e-sheet--v0.5.10;
times-up--v0.8.10;
token-action-hud--v1.1.15;
token-attacher--v4.1.2;
token-hud-wildcard--v1.3.1;
token-info-icons--v2.3.2;
token-mold--v2.13.1;
tokenmagic--v0.5.2.1;
trigger-happy--v0.8.7;
wall-height--v3.5.3.9;
zoom-pan-options--v1.6.5;
_CodeMirror--v5.58.3-fvtt3;
_mathjs--v7.5.1-fvtt2;
_sortablejs--v1.10.2-fvtt1;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by Ethck** [comment]
And so it does. Thankfully this isn't anything major, but thanks for pointing it out!

**Comment by Ethck** [comment]
This is intended (because you are supposed to make a selection on the first screen), but I can add a reason to make it more clear.

**Comment by Djahal** [comment]
> This is intended (because you are supposed to make a selection on the first screen), but I can add a reason to make it more clear.

Ok, no big deal, thank you for explaining :).
