### ISSUE TITLE
Info button on item card doesn't add to chat

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/bug-reporter#116]
**Submitted By**: editbag@gmail.com
**Feedback Type**: Bug
 
**Core:** 0.8.8
**System:** dnd5e v1.4.1
**Module Version:** bug-reporter v1.3.2
 
**Description**:
Foundry 8.8, D&D 5e 1.4.1
- Clicking on the info button on an item within a character sheet no longer sends the item with the info into chat.<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

bug-reporter--v1.3.2;
lib-wrapper--v1.8.0.0;
midi-qol--v0.8.38;
socketlib--v1.0.8;
tidy-ui_game-settings--v0.1.23;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by Ethck** [comment]
This looks like it was meant for the D&D 5e system, not bug reporter. Closing.
