### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/bug-reporter#121]
**Core:** 0.8.9
**System:** ma20th v1.0.1
**Module Version:** bug-reporter v1.3.2
 
**Description**:
No funciona el modulo de Mago 20TH<details>
<summary>Active Modules</summary>

bug-reporter--v1.3.2;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by anthonyronda** [comment]
Closing as incorrect recipient
