### ISSUE TITLE
Small UI nitpick: Button is not the same width as the rest

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/bug-reporter#67]
**Submitted By**: flamewave000, flamewave#6766
**Feedback Type**: Enhancement
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** bug-reporter v1.0.0
 
**Description**:
The button is just slightly larger than the rest of the buttons on the settings page. The others are in containers with an `8px` left-right margin.

```css
.bug-report {
    margin: 0 8px;
}
```

When ever you make your next update, it'd be cool if you added the same margin to your button 👍

**Comment by flamewave000** [comment]
Your module is great, and I'm really happy to see a well-done way for users to submit issues in a nice and easy way. Many don't even know about GitHub or how to report things. Good job 🙂

**Comment by akrigline** [comment]
@flamewave000 did you use ``` in your description on the module and did it "just work"? 😍

**Comment by Ethck** [comment]
Same as #55

**Comment by flamewave000** [comment]
@akrigline that is exactly what I did :+1: I knew it was coming to GitHub and that GitHub stores all original Markdown, so I thought I'd try it 😋 I also used `` ```css `` to start the code block so it would syntax highlight.

@Ethck Sorry for the duplicate issue

**Comment by Ethck** [comment]
No worries @flamewave000 it's more for my sanity to know that they are duplicates. If anything, your code sample is very nice :)
